### ISSUE TITLE
Getting -bash: standard-readme-linter-regex: command not found

### ISSUE THREAD

**Issue by lukasoppermann** [RichardLitt/standard-readme-linter-regex#7]
Hey,

I installed it using npm and now I am getting this:

`-bash: standard-readme-linter-regex: command not found`

Where did I screw up? Any ideas? Installed it globally like suggested. Thanks, appreciate the whole standard-readme effort. 👍

**Comment by RichardLitt** [comment]
I think this one is not an issue? Should be `srlr`. But it looks like you caught that! \o/
